
import { createClient } from '@supabase/supabase-js';

// Initialize the Supabase client
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Check if Supabase URL and anon key are available
if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Supabase URL or Anon Key is missing. Please set the VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY environment variables.');
}

// Create the Supabase client only if the URL and anon key are available
const supabase = supabaseUrl && supabaseAnonKey 
  ? createClient(supabaseUrl, supabaseAnonKey)
  : null;

interface OpenAIRequestParams {
  prompt: string;
  model: string;
  temperature?: number;
  maxTokens?: number;
}

interface OpenAIResponse {
  text: string;
  success: boolean;
  error?: string;
}

export const callOpenAI = async (params: OpenAIRequestParams): Promise<OpenAIResponse> => {
  try {
    console.log('Calling OpenAI with params:', params);
    
    // If Supabase client is not available, use mock response
    if (!supabase) {
      console.warn('Supabase client not initialized. Using mock response.');
      return {
        text: generateMockResponse(params.prompt),
        success: true
      };
    }
    
    // Call the Supabase Edge Function
    const { data, error } = await supabase.functions.invoke('openai', {
      body: params
    });
    
    if (error) {
      console.error('Error calling OpenAI edge function:', error);
      // Fall back to mock response if the edge function fails
      return {
        text: generateMockResponse(params.prompt),
        success: true,
        error: error.message || 'Failed to generate content. Using fallback response.'
      };
    }
    
    console.log('OpenAI response:', data);
    return data as OpenAIResponse;
  } catch (error) {
    console.error('Error calling OpenAI:', error);
    // Fall back to mock response on any error
    return {
      text: generateMockResponse(params.prompt),
      success: true,
      error: 'Failed to generate content. Using fallback response.'
    };
  }
};

// This function is kept for fallback in case the edge function fails
function generateMockResponse(prompt: string): string {
  // In a real implementation, this would be the response from OpenAI
  if (prompt.includes('executive summary')) {
    return 'This is a mock executive summary generated based on your business information. It would provide a concise overview of your business concept, target market, and objectives.';
  } else if (prompt.includes('market analysis')) {
    return 'This is a mock market analysis that would normally include industry trends, competitor analysis, and target audience insights generated by the AI.';
  } else if (prompt.includes('business model')) {
    return 'This is a mock business model section that would explain revenue streams, pricing strategies, and operational structure based on your inputs.';
  } else {
    return 'This is a generic mock response. In a real implementation, this would be replaced with actual content generated by OpenAI.';
  }
}
