// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxnhpkyviyvoefbgyzgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bmhwa3l2aXl2b2VmYmd5emdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MzIwNTIsImV4cCI6MjA1ODEwODA1Mn0.gVkFqkGbFTEImya4R-qxmr9UKRc6YxxwQGPhyZRMUSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);